Aporte de Tutorial Go - Prog Concurrente
ferestrepoca/paradigmas-de-programacion pull request #121
Opened 2019-07-11 17:56 UTC by Juankmilo97

# Tutorial de Go - Programación Concurrente

## Contenido:
- Sintáxis del Lenguaje
- Conceptos de Prog. Concurrente en Go (Hilos Ligeros, Canales y Tamaño de Canales, Canales con Exclusión Mutua, etc)
- Ejemplos de código adicionales que ayudan a entender el funcionamiento de Métodos, Interfaces, Channels (& Buffered Channels), Sync.Mutex.

2019-07-12 00:56 UTC, ferestrepoca requested changes
¿Este notebook reemplaza completamente el existente (progconcurrente/tutoriales/GO/Tutorial-GO.ipynb)? ¿o lo complementa? 

También, debería haber un link al nuevo notebbok: progconcurrente/tutoriales/GO/ProgConcurrente_Tutorial.ipynb

2019-07-12 12:24 UTC, Juankmilo97 commented
Lo complementa profe. Claro que sí profe, apenas quedé subido en el repo yo subo ese link a la presentación para que tengan acceso a ambos.

2019-07-13 15:33 UTC, ferestrepoca commented
@Juankmilo97 El enlace al nuevo notebook (que hasta donde entiendo, complementa el anterior) debe estar en la página principal de paradigmas. Sino, será muy difícil encontrar este recurso.

2019-07-14 19:33 UTC, Juankmilo97 commented
@ferestrepoca Listo profe, ya entendí que olvidé cambiar sobre el index.html. Ya corregí y quedó el link pertinente al nuevo tutorial que complementa en ejemplos y demás el tutorial anterior.

2019-07-15 00:37 UTC, ferestrepoca approved these changes

2019-07-15 00:37 UTC, merged