Add DCG example and some changes
ferestrepoca/paradigmas-de-programacion pull request #135
Opened 2020-06-02 02:16 UTC by anferoar96

Add DCG example and some changes

2020-06-09 23:35 UTC, ferestrepoca requested changes
Por favor hacer los ajustes para poder aprobar el PR.

2020-06-09 23:35 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +  se muestra a continuacion
Por favor corregir ortografía y símbolos de puntuación.

2020-06-09 23:35 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +  posee para representar la gramatica por medio de DCG:
Corregir ortografía y puntuación.

2020-06-09 23:35 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +  mediante el uso de DCG la gramatica con la queremos trabajar.Y la forma como se realizan consultas sobre si una estructura
Ortografía y dejar espacio en blanco después de "."

2020-06-09 23:35 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> + tarea de revision al lector.
Corregir ortografía

2020-06-11 15:16 UTC, anferoar96 commented
Profe ya fueron solucionados los problemas de ortografia

2020-06-11 15:23 UTC, anferoar96 commented
Tambien se soluciono problema de conflicto con la rama principal

2020-06-11 19:32 UTC, ferestrepoca approved these changes

2020-06-11 19:32 UTC, merged