Arreglos al prolog alrramirezso
ferestrepoca/paradigmas-de-programacion pull request #136
Opened 2020-06-02 03:18 UTC by alreraso

Integrantes:

Alrramirezso

Se agrega en la parte de aplicaciones los aportes de prolog en la quinta generación de computadores.

Se agrego una modificación de aling="justify" a el texto para darle estilo a la pagina para una mejor lectura.

Se agrego una imagen que describe la traducción  de un lenguaje a otro (Japones -  ingles).

2020-06-09 23:42 UTC, ferestrepoca requested changes
Por favor hacer los ajustes menores solicitados para proceder a aprobar el PR.

2020-06-09 23:42 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p align="justify">Aunque el proyecto no tuvo  un resultado satisfactorio fue un gran avance para lo que hoy en dia conocemos como las traducciones automaticas princiupalmente en paginas web.</p>
Corregir ortografía, puntuación, y la palabra "quitan".

2020-06-09 23:42 UTC, ferestrepoca commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Alci René Ramírez Soto.</p>
Alinear como los demás compañeros.

2020-06-10 01:35 UTC, alreraso commented
Correcciones aplicadas profe

2020-06-10 01:38 UTC, merged