feat(proglogica/logica_teoria/aplicaciones.html):agregada pagina de a…
ferestrepoca/paradigmas-de-programacion pull request #138
Opened 2020-06-02 04:57 UTC by luealfonsoru

…plicaciones

2020-06-10 00:09 UTC, ferestrepoca requested changes
Por favor hacer los ajustes menores para proceder a aprobar el PR.

2020-06-10 00:09 UTC, ferestrepoca commented on proglogica/logica_teoria/aplicaciones.html
> +                    <h2 id="Lenguajes">Aplicaciones:</h2>
Usar id="Aplicaciones"

2020-06-10 00:09 UTC, ferestrepoca commented on proglogica/logica_teoria/aplicaciones.html
> +                        su correlación con </p>
Completar la idea: "...su correlación con" ?

2020-06-10 00:09 UTC, ferestrepoca commented on proglogica/logica_teoria/aplicaciones.html
> +                        no terminales) que son términos lógicos.
Borrar saltos de línea innecesarios y en la doble coma ", ," dejar solo una ",".

2020-06-11 22:57 UTC, luealfonsoru commented on proglogica/logica_teoria/aplicaciones.html
> +                        no terminales) que son términos lógicos.
@ferestrepoca  Listo, ya se realizaron los cambios: mil gracias!

2020-06-11 23:21 UTC, ferestrepoca approved these changes

2020-06-11 23:21 UTC, merged