aportes grupo programacion funcional teorica 2020-2
ferestrepoca/paradigmas-de-programacion pull request #159
Opened 2020-11-26 02:57 UTC by bdvegat

Enviamos los aportes de:
Bryan David Vega Triana
Cristian Camilo Aguilera Polanco
Lorraine Jazlady Rojas Parra
Juan David Solano Salazar
del grupo de programación funcional teoria 2020-2.

2020-11-26 15:35 UTC, ferestrepoca requested changes
Please correct multiple typos and orthographic errors. I've pointed out some of them.
This is required before merging this PR. Thanks!

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/applications.html
> +                                ReactiveX es una lbreria para la composición de funciones asyncronas y programas basados en eventos usando secuencias obsevables.
Fix typos like

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/applications.html
> +                                ReactiveX es una lbreria para la composición de funciones asyncronas y programas basados en eventos usando secuencias obsevables.
Fix this

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/applications.html
> +                                ReactiveX es una lbreria para la composición de funciones asyncronas y programas basados en eventos usando secuencias obsevables.
Fix this

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/examples.html
> +                <h1>Funciones anonimas</h1>
Fix

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/examples.html
> +                <h1>Curryng</h1>
Fix

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/examples.html
> +                <h1>Efecct tracking</h1>
Fix

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/examples.html
> +                <h1>Vectotización</h1>
Fix

2020-11-26 15:35 UTC, ferestrepoca commented on progfun/funcional_teoria/referencias.html
> +                        Imagenes interactivas de las categorías (Functor, Aplicativos, Monadas, etc)
Fix this

2020-11-27 00:10 UTC, bdvegat commented
Fixed, please review.

2020-11-27 01:05 UTC, ferestrepoca approved these changes

2020-11-27 01:05 UTC, merged