Programacion paralela teoria, aporte por Sebastian Guerrero Salinas, …
ferestrepoca/paradigmas-de-programacion pull request #162
Opened 2020-11-30 04:28 UTC by SebWarr

…mejora de orden de conceptos clave, justificacion textos, ortografia y algunos nuevos conceptos con imagenes

2020-11-30 04:30 UTC, SebWarr commented
Aporte por Sebastian Guerrero Salinas

2020-12-02 20:02 UTC, ferestrepoca requested changes
Por favor revisar el Pull Request ya que solo aparecen algunos archivos de imágenes nuevos pero no se utilizan en el sitio web. Los cambios anunciados en el comentario del PR no están presentes. Gracias.

2020-12-03 20:34 UTC, ferestrepoca requested changes
Sigue igual. Por favor revisar bien para no evitar reprocesos.

2020-12-03 20:49 UTC, SebWarr commented
Profe me encuentro terminando los cambios que volví a hacer desde ceros, tan pronto acabe el ECAES termino e intento subir los cambios

2020-12-04 05:08 UTC, SebWarr commented
Ya realicé un nuevo push con los cambios profesor, ¿me podría por favor indicar si subieron correctamente y si está todo bien?
Me aparecen dos conflictos
Quedo atento
Gracias

2020-12-04 22:57 UTC, ferestrepoca approved these changes

2020-12-04 22:57 UTC, merged