se aporta ciclos de vida en poa, presentacion y ejemplo
ferestrepoca/paradigmas-de-programacion pull request #204
Opened 2022-06-16 03:59 UTC by cdtafurd

Cristian David Tafur Devia
Diego Alejandro Gutierrez Rojas
Juan Camilo Pineda Vargas
Christian Camilo Rojas Tapias
Se aporta:
En la página de Filosofia del paradigma se añade la sección Características generales del desarrollo de software orientado a aspectos 
Se añade la presentación en la página de presentaciones
Se añade el ejemplo 5 saludo a clase de LP en la paǵina de ejemplos

2022-06-16 15:10 UTC, ferestrepoca requested changes

2022-06-16 15:10 UTC, ferestrepoca commented on poa/poa_teoria/Pages/ejemplos.html
> +  <script src="https://ideone.com/e.js/dR4udj" type="text/javascript" ></script>
Los scripts deben quedar en el repositorio de paradigmas-de-programacion.

2022-06-16 18:55 UTC, cdtafurd commented on poa/poa_teoria/Pages/ejemplos.html
> +  <script src="https://ideone.com/e.js/dR4udj" type="text/javascript" ></script>
Ya hice el cambio a como están en otras partes del código.

2022-06-16 19:46 UTC, ferestrepoca requested changes

2022-06-16 19:46 UTC, ferestrepoca commented on poa/poa_teoria/Pages/ejemplos.html
> +  <script src="https://gist.github.com/cdtafurd/4e418f10e04cc19d5a818a4d8fc820d5.js"></script>
Los scripts siguen estando por fuera del repositorio de paradigmas. Por favor revisar con atención.
Tampoco es válido cambiarlos por imágenes, pues perdería la posibilidad de manipular el código con facilidad.

2022-06-16 23:22 UTC, cdtafurd commented on poa/poa_teoria/Pages/ejemplos.html
> +  <script src="https://gist.github.com/cdtafurd/4e418f10e04cc19d5a818a4d8fc820d5.js"></script>
Profe, la forma que encontre, y que en otros lugares del repo también se usa, fue usando las etiquetas <pre> y <code>, permitiendo visualizar el bloque de código. Evita a hacer referencia a archivos fuera del repositorio.

2022-06-17 00:27 UTC, ferestrepoca approved these changes

2022-06-17 00:27 UTC, merged