Nuevo ejemplo prolog
ferestrepoca/paradigmas-de-programacion pull request #206
Opened 2022-11-02 13:47 UTC by geramirezl

Integrantes: 
jpereirap - geramirezl -  jedcastroag - nacaicedol

Se agrega presentación con tutorial prolog
Se agrega ejemplo sistema expertos de animales

2022-11-03 02:52 UTC, jubustamantem requested changes
Por favor, revisar las correcciones ortotipográficas y de estilo sugeridas, y aceptar las que se consideren pertinentes.

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p align="justify">Implementacion de un Sistema Experto en prolog que identifique un animal de un conjunto de animales definidos por características:</p>
```suggestion
<p align="justify">En este ejemplo se lleva a cabo la implementación de un Sistema Experto en prolog que permite identificar un animal dentro de un conjunto de animales definidos por características.</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p align="justify">Un sistema experto es un sistema computacional que emula la capacidad de tomar decisiones de un humano experto. Está compuesto por una base de conocimiento y un motor de inferencia
```suggestion
<p align="justify">Un sistema experto es un sistema computacional que emula la capacidad de tomar decisiones de un humano experto. Está compuesto por una base de conocimiento y un motor de inferencia, el cual recibe las características de una entidad o un problema. Comparando el conocimiento previo existente en la base de conocimientos con las características de la entidad es posible identificarlo y, en consecuencia, producir un diagnóstico o deducción.
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Primero se define la regla, con la cual se inicia el proceso, que llama a las hipotesis, que hace el proceso para evaluar las hipotesis y luego escribir en consola la solucion final </p>
```suggestion
<p>Primero se define la regla, con la cual se inicia el proceso. Esta regla llama a las hipótesis, luego realiza el proceso para evaluarlas y, finalmente, escribe en consola la solución final.</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p align="justify">Se definen una lista de hipotesis que van a ser puestas a prueba, estas hipotesis son excluyentes entre ellas ( el animal no puede ser un tigre y una jirafa al mismo tiempo) </p>
```suggestion
<p align="justify">Se define una lista con las hipótesis que van a ser puestas a prueba. Estas hipótesis son excluyentes entre ellas (por ejemplo, el animal no puede ser un tigre y una jirafa al mismo tiempo). </p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Luego identificamos las caracteristicas que tiene cada animal por las cuales se puede diferenciar</p>
```suggestion
<p>Luego, se identifican las características por las cuales se puede diferenciar cada animal.</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Cada caracteristica de animal llama a verificar para preguntar al usuario si el animal que busca tiene la caracteristica que pregunta, con esta información para alimentar a la base de conocimiento
```suggestion
<p>Se puede ver que cada una de ellas llama a "verificar"; de esta manera, se le preguntará al usuario si el animal que busca tiene una característica en particular. Con esta información se alimenta la base de conocimiento.</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p align="justify">La regla auxiliar "ask" sirve para recibir los datos del usuario, esta hace uso de la regla assert que trae prolog por defecto para poder añadir nuevos hechos a la base de conocimi
```suggestion
<p align="justify">La regla auxiliar "ask" sirve para recibir los datos del usuario: esta hace uso de la regla "assert" que trae prolog por defecto, la cual permite añadir nuevos hechos a la base de conocimiento del sistema.</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Ejemplos de la salida del sistema:</p>
```suggestion
<h3>Ejemplos de la salida del sistema</h3>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Resultado de busqueda de zebra</p>
```suggestion
<p>Resultado de búsqueda de <strong>zebra<strong>:</p>
```

2022-11-03 02:52 UTC, jubustamantem commented on proglogica/tutoriales/prolog-gh-pages/index.html
> +<p>Resultado de busqueda de jaguar</p>
```suggestion
<p>Resultado de búsqueda de <strong>jaguar</strong>:</p>
```

2022-11-05 17:35 UTC, jubustamantem approved these changes
Perfecto, ¡muchas gracias!

2022-11-08 13:50 UTC, ferestrepoca approved these changes

2022-11-08 13:53 UTC, merged