Proglogica 20222 teoria
ferestrepoca/paradigmas-de-programacion pull request #207
Opened 2022-11-06 19:40 UTC by JuanCll

Integrantes:
Andrés Felipe López Gutiérrez
Diego Alejandro Carvajal Beltrán
Harold Alfredo Díaz Ortiz
Juan Felipe Callejas Fracica

Se añadieron aplicaciones de la programación lógica.
Se añadió en las aplicaciones el paradigma de la programación lógica probabilística, un lenguaje de este y un ejemplo.
Se añadieron ejemplos de aplicación de Prolog en dos plataformas.
Se añadieron las referencias correspondientes a lo anterior.

2022-11-11 04:45 UTC, jubustamantem requested changes
Revisar las correcciones sugeridas y aplicar las que se consideren pertinentes. Además, evaluar la posibilidad de incluir el material que hayan utilizado para exponer en clase (archivo .pdf) en la sección "presentaciones de semestres anteriores".

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        probabilísticos y la inferencia a partir de estos modelos se realizan automáticamente.
```suggestion
                        probabilísticos y la inferencia a partir de estos modelos se realiza automáticamente. 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        Además se ha utilizado como un subcampo de la inteligencia artificial, el cual incluye a
```suggestion
                        Además, se ha utilizado como un subcampo de la inteligencia artificial, el cual incluye a 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        los lenguajes de programación tradicionales estructuras para trabajar con inferencia probabilística
```suggestion
                        los lenguajes de programación tradicionales estructurados para trabajar con inferencia probabilística 
```
O modificarlo de acuerdo con lo que se haya querido decir.

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        Además ha mostrado utilidad en diferentes áreas de aplicación gracias a su forma particular
```suggestion
                        Además, ha mostrado utilidad en diferentes áreas de aplicación gracias a su forma particular 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        del concepto de probabilidad, generando en este caso la programación lógica probabilística.
```suggestion
                        del concepto de probabilidad, generando, en este caso, la programación lógica probabilística. 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                        ocurrir siempre, como ocurre en la vida real.
```suggestion
                        ocurrir siempre tal como ocurren en la vida real.
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    Desde una perspectiva de modelado, se puede considerar que un programa de Problog está compuesto por dos partes,
```suggestion
                                    Desde una perspectiva de modelado, se puede considerar que un programa de Problog está compuesto por dos partes: 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    una parte probabilística que define una distribución de probabilidad sobre los valores de verdad  y otra logica que
```suggestion
                                    una parte probabilística que define una distribución de probabilidad sobre los valores de verdad, y otra lógica que 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                <p>Ejemplo en Problog
```suggestion
                                <p><strong>Ejemplo en Problog:</strong>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    0.4::asthma(X) :- smokes(X). <br>
```suggestion
                                    <code> 0.4::asthma(X) :- smokes(X). <br> </code>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    0.3::smokes(X). <br>
```suggestion
                                    <code> 0.3::smokes(X). <br> </code>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    0.2::smokes(X) :- friend(X,Y), smokes(Y). <br>
```suggestion
                                    <code> 0.2::smokes(X) :- friend(X,Y), smokes(Y). <br> </code>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    friend(1,2). friend(2,1). friend(2,4). friend(3,2). friend(4,2).<br>
```suggestion
                                    <code> friend(1,2). friend(2,1). friend(2,4). friend(3,2). friend(4,2).<br> </code>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    tenga éxito, por ejemplo ?- asthma(2) tiene éxito con una probabilidad de 0,15. Si añadimos asthma(3) como evidencia,
```suggestion
                                    tenga éxito, por ejemplo <code>?- asthma(2)</code> tiene éxito con una probabilidad de 0,15. Si añadimos <code>asthma(3)</code> como evidencia, 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    la probabilidad condicional de ?- asthma(2) es de 0,19.
```suggestion
                                    la probabilidad condicional de <code>?- asthma(2)</code> es de 0,19.
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    más modernos. Este lenguaje además presenta grandes aplicaciones en el ámbito de la
```suggestion
                                    más modernos. Este lenguaje, además, presenta grandes aplicaciones en el ámbito de la 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    inteligencia artificial además que permite modelar y obtener respuestas rápidamente
```suggestion
                                    inteligencia artificial; incluso permite modelar y obtener respuestas rápidamente, 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                                    además de la capacidad de tratar conjuntos de datos muy grandes.
```suggestion
                                    pues cuenta con la capacidad de tratar conjuntos de datos muy grandes.  
```
Eliminación de repeticiones de la palabra "además".

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
>          Content Section
Las siguientes subsecciones ("Creación de prototipos" y "Simulación") están vacías. Revisarlas y agregar contenido (o considerar removerlas).

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/lenguaje.html
> +          <p>Genexus y Linx: plataformas Low-code desarrolladas utilizando Prolog. <br>
```suggestion
          <ul><li><strong>Genexus y Linx:</strong> plataformas Low-code desarrolladas utilizando Prolog. <br>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/lenguaje.html
> +            Low- code es un modalidad de desarrollo de software que permite que los programadores diseñen aplicaciones
```suggestion
            Low-code es una modalidad de desarrollo de software que permite que los programadores diseñen aplicaciones
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/lenguaje.html
> +            rápidamente y con un mínimo de codificación manual a través de un sistema de arrastrar y soltar.
```suggestion
            rápidamente y con un mínimo de codificación manual por medio de un sistema de arrastrar y soltar. 
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/lenguaje.html
> +            </p>
```suggestion
            </li></ul>
```

2022-11-11 04:45 UTC, jubustamantem commented on proglogica/logica_teoria/aplicaciones.html
> +                            <li><a href="aplicaciones.html#Logica_probabilistica">Programación lógica probabilística</a></li>
Esta línea de código también debería agregarse en el menú de navegación de todos los otros archivos .html de la carpeta logica_teoria para que sea posible acceder al nuevo contenido desde cualquier punto de la página.

2022-11-14 00:19 UTC, jubustamantem approved these changes
Perfecto, muchas gracias.

2022-11-15 13:51 UTC, ferestrepoca approved these changes

2022-11-15 13:54 UTC, merged