Contribution Progfun
ferestrepoca/paradigmas-de-programacion pull request #208
Opened 2022-11-09 16:55 UTC by joviedog

shernandezch - ilombana -joviedog -  rtoleadol

- Se añadieron ventajas a la sección de paralelismo, explicando thread-safety y race conditions
- Se añadieron desventajas asociadas a conceptos
- Corrección de errores ortográficos
- Nuevo ejemplo en Python sobre el uso de map.
- Ajuste visual a la sección de código en Kotlin ajustando el host de código a Gist.
- Creación de una sección adicional con recursos de aprendizaje autonomo (MOOCS)

2022-11-11 05:26 UTC, jubustamantem requested changes
Revisar las correcciones y las sugerencias realizadas. Aplicar las que se consideren pertinentes.

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                                El uso de Lazy Evaluation permite optimizar el tiempo necesario para realizar computaciones,
```suggestion
                                El uso de Lazy Evaluation permite optimizar el tiempo necesario para realizar computaciones. 
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                                multiples plataformas de Big Data, como Apache Spark, hacen uso del paradigma para obtener estos
```suggestion
                                Múltiples plataformas de Big Data, como Apache Spark, hacen uso del paradigma para obtener estos
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                                del uso de funciones netamente impuras. Un programa que provea utilidad al usuario requerirá, en la gran mayoría de casos,
```suggestion
                                de funciones netamente impuras. Un programa que provea utilidad al usuario necesitará, en la gran mayoría de casos, 
```
Eliminación de palabras repetidas ("el uso", "requerir").

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                            los objetos que son inmutables, se vuelven automaticamente seguros en el manejo de hilos (o
```suggestion
                            los objetos que son inmutables, se vuelven automáticamente seguros en el manejo de hilos (o
```
Revisar otros errores de ortografía presentes en este párrafo (Característica*, código*, ningún*).

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                            (Multexes , Semaforos ,Locks) por lo cual se pueden ralizar funciones en paralelo siempre que
```suggestion
                            (Multexes, Semáforos, Locks) por lo cual se pueden realizar funciones en paralelo siempre que
```
Por favor también revisar la ortografía en este párrafo.

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                            Por otro lado, la concurrencia es mucho más segura, las funciones puras son seguras para hilos (thread-safe), es decir, siempre
```suggestion
                            Por otro lado, la concurrencia es mucho más segura. Las funciones puras son seguras para hilos (thread-safe), es decir, siempre
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                            tiempo. Esto se conoce como condiciones de carrera y es uno de los bugs más dificiles de solucionar, dado que las
```suggestion
                            tiempo. Esto se conoce como condiciones de carrera y es uno de los bugs más difíciles de solucionar; dado que las
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                            funciones puras nunca comparten estados con las demás secciones de un programa nunca tienen condiciones de carrera.
```suggestion
                            funciones puras nunca comparten estados con las demás secciones de un programa, nunca tienen condiciones de carrera.
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                        <div class="col-md-6">
Pasar este div atrás del anterior para mantener la uniformidad en el estilo de la página (JAVA 8+ y PYTHON llevan el texto en la columna de la izquierda y las imágenes/notebooks en la columna de la derecha; esta debería llevar el texto en la columna derecha y la imagen con el notebook en la columna izquierda, dado que se van intercalando las posiciones).

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                                dinámico, junto a su naturaleza interpretada lo convierten en un lenguaje ideal para scripting y desarrollo rápido de
```suggestion
                                dinámico, junto a su naturaleza interpretada, lo convierten en un lenguaje ideal para scripting y desarrollo rápido de
```

2022-11-11 05:26 UTC, jubustamantem commented on progfun/funcional_teoria/index.html
> +                                aplicaciones en muchas áreas, para la mayoría de plataformas.
```suggestion
                                aplicaciones en muchas áreas para la mayoría de plataformas.
```

2022-11-14 00:14 UTC, jubustamantem approved these changes
Perfecto, muchas gracias.

2022-11-15 14:00 UTC, ferestrepoca approved these changes

2022-11-15 14:00 UTC, merged