Progreactiva 20222 practica
ferestrepoca/paradigmas-de-programacion pull request #214
Opened 2022-11-16 18:19 UTC by nrrf

2022-11-16 18:26 UTC, nrrf commented
Integrantes: 
Nicolas Raul Rojas  
Harold Bartolo 
Mateo Herrera  
Kevin Ibarra  

Se creo desde el inicio la pagina de RxJS

2022-11-25 00:19 UTC, ferestrepoca requested changes

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					<li><a href="#three">Practica</a></li>
```suggestion
					<li><a href="#two">Características específicas</a></li>
					<li><a href="#three">Práctica</a></li>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					eventos a traves de la combinacion del patron Observer e Iterator.
```suggestion
					ReactiveX es un API que extiende del <a href="https://en.wikipedia.org/wiki/Observer_pattern">patrón
						observador</a>
					para programación asíncrona que facilita el manejo de flujo de datos y
					eventos a través de la combinación del patrón Observer e Iterator.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							El cual proporciona tres tipos de elementos pricipales:
```suggestion
							Proporciona tres tipos de elementos pricipales:

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							manejo de errores si su compresión se hace más dificil.
```suggestion
							manejo de errores y su compresión se hace más dificil.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +						<p>Es cuando las promesas son utiles, para realizar el manejo de errores y realizar
```suggestion
						<p>Es cuando las promesas son útiles, para realizar el manejo de errores y realizar

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							y no es muy útil cuando operación asíncronano termina tras un valor.
```suggestion
						<p>Pero las promesas presentan la limitación de que solo pueden manejar una operación asíncrona
							por promesa
							y no es muy útil cuando la operación asíncrona no termina tras un valor.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							errores con facilidad desde el <i>subscribe</i>.
```suggestion
						<p>Como ejemplo tomamos el caso de un botón cualquiera, el cual puede ser oprimido múltiples
							veces,
							de forma que el método <i>subscribe()</i> se suscribe a todos los eventos reconocidos por el
							<i>Observable</i>, reaccionando a cada uno de ellos. Adicionalmente se puede realizar el
							manejo de
							errores con facilidad desde el <i>subscribe</i>.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +								y sea más atractiva y alcanzable.
```suggestion
							<dd>Es una herramienta funcional y poderosa, haciendo que su popularidad aumente
								y sea más atractiva y alcanzable.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							<dd>Es una herramienta que es compatible con gran cantidad de frameworks y lenguejes.</dd>
```suggestion
							<dd>Es una herramienta que es compatible con gran cantidad de frameworks y lenguajes.</dd>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +								permitiendo concentrarse en la lógica.
```suggestion
							<dd>Proporciona una API elegante que facilita la descripción de flujos complejos, incluyendo
								un completo set de entidades que se encargan del trabajo pesado, ocultando la complejidad, lo que permite concentrarse en la lógica.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							<dd>Su amplia colección de operadores faicilita la progrmación</dd>
```suggestion
							<dd>Su amplia colección de operadores facilita la programación</dd>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							<dt>Documentacion</dt>
```suggestion
							<dt>Documentación</dt>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +								erroes.</dd>
```suggestion
							<dd>Cuenta con actualizaciones regulares, añadiendo constantemente mejoras y corrección de
								errores.</dd>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +								especificas de la programación reactiva.
```suggestion
								Su depuración y pruebas es algo difícil para un ojo inexperto debido a algunas funciones
								específicas de la programación reactiva.

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					y de la libreria RxJS</h4>
```suggestion
				<h1>Características específicas</h1>
				<h4>A continuación vamos a dar una serie de explicaciones de conceptos clave de la programación reactiva
					y de la librería RxJS</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					propagacion de cambio</h4>
```suggestion
				<h4>La programación reactiva es la programación orientada al manejo de Streams de datos asíncronos y la
					propagación de cambio</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Rx es una combinacion de las mejores ideas del patron observer y el patron iterator</h4>
```suggestion
				<h2>La librería ReactiveX en pocas palabras</h2>
				<h4>Rx es una combinación de las mejores ideas del patrón observer y el patrón iterator</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Una manera grafica de mostrar lo que es un stream de datos es a traves de un diagrama de canicas,
```suggestion
				<h4>Una manera gráfica de mostrar lo que es un stream de datos es a través de un diagrama de canicas,

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Por ejemplo con un flujo de datos que emite numeros del 0 al 3, tendriamos lo siguiente:</h4>
```suggestion
				<h4>Por ejemplo con un flujo de datos que emite números del 0 al 3, tendríamos lo siguiente:</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>La estructura del patron iterator es la siguiente: </h4>
```suggestion
				<h2>Patrón Iterator</h2>
				<h4>Iterator es un patrón de diseño de comportamiento que te permite recorrer elementos de una colección
					sin exponer su representación subyacente (lista, pila, árbol, etc.).</h4>
				<h4>La estructura del patrón iterator es la siguiente: </h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Ejemplo: código de Java que nos muestra el funcionamiento de este patron para hacer la concatenación
```suggestion
				<h4>Ejemplo: código de Java que nos muestra el funcionamiento de este patrón para hacer la concatenación

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h2>Patron Observador</h2>
```suggestion
				<h2>Patrón Observador</h2>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					cualquier momento puede romper esta suscripcion dejando de seguir la cuenta</h4>
```suggestion
				<h4>La imagen de arriba no solo nos muestra el funcionamiento del patrón observador, sino que nos da un
					analogía del mismo cuando se sigue una cuenta de twitter. Al suscribirse a una
					cuenta (observable), el seguidor (observador) va a ser notificado de los tweets nuevos de la cuenta y en
					cualquier momento puede romper esta suscripción, dejando de seguir la cuenta.</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Pull y Push representan diferentes protocolos que describen como se relaciona el productor de datos
```suggestion
				<h4>Pull y Push representan diferentes protocolos que describen cómo se relaciona el productor de datos

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +						<td>Activo: Decide cuando necesita los datos</td>
```suggestion
						<td>Activo: Decide cuándo necesita los datos</td>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +					llama a la función consumiendo el retorno.</h4>
```suggestion
				<h4>Pull: En un sistema Pull el consumidor determina cuándo quiere recibir datos del productor. El
					productor en sí mismo se despreocupa de cuándo se enviarán los datos al consumidor. Por ejemplo,
					todas las funciones JS son de tipo Pull; las funciones son productoras de datos y el código que las
					llama consume su valor de retorno.</h4>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Push: El productor determina cuando enviar los datos al consumidor, un ejemplo típico es un servidor
```suggestion
				<h4>Push: El productor determina cuándo enviar los datos al consumidor. Un ejemplo típico es un servidor

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h2>Observadores Frios VS Calientes</h2>
```suggestion
				<h2>Observadores Fríos VS Calientes</h2>

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<h4>Frio: Los Observables "fríos" son aquellos que no emiten valores hasta que haya una suscripción
```suggestion
				<h4>Frío: Los Observables "fríos" son aquellos que no emiten valores hasta que haya una suscripción

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +				<p>RxJS es principalmente útil para sus operadores , aunque el Observable es la base. Los operadores son
```suggestion
				<p>RxJS es principalmente útil por sus operadores. Aunque el Observable es la base, los operadores son

```

2022-11-25 00:19 UTC, ferestrepoca commented on reactive/tutoriales/ReactiveX/index.html
> +							Observable. Por ejemplo: of(1, 2, 3)crea un observable que emitirá 1, 2 y 3, uno tras otro.
```suggestion
							Observable. Por ejemplo: of(1, 2, 3) crea un observable que emitirá 1, 2 y 3, uno tras otro.

```

2022-11-25 00:21 UTC, ferestrepoca approved these changes

2022-11-25 00:21 UTC, merged