Programacion concurrente Teoria Aplicaciones del paradigma
ferestrepoca/paradigmas-de-programacion pull request #216
Opened 2022-11-21 14:06 UTC by mmedranom

Integrantes que aportan en este commit:
Manuel David Medrano Monroy

-Se amplía la sección de aplicaciones de paradigmas, agregando introducción y aplicaciones en software extendidas
-Se anexan imágenes nuevas

2022-11-22 04:19 UTC, jubustamantem requested changes
Revisar correcciones sugeridas y aceptar las que se consideren necesarias.

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                En la cotidianeidad encontramos muchos ejemplos de concurrencia y paralelismo en múltiples procesos con los que interactuamos continuamente, de ellos podemos abstraer características
```suggestion
                En la cotidianeidad encontramos muchos ejemplos de concurrencia y paralelismo en múltiples procesos con los que interactuamos continuamente. De ellos podemos abstraer características propias que los identifican, así como las partes que los conforman, con el fin de tratar de entender y modelarlos en un entorno virtual.
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                El mundo real contiene actores que ejecutan acciones independientemente, pero se comunican entre sí al realizarlas, es por esto que al modelar el mundo, se deben componer y coordinar
```suggestion
                El mundo real contiene actores que ejecutan acciones independientemente, pero que se comunican entre sí al realizarlas. Es por esto que, al modelar el mundo, se deben componer y coordinar muchas ejecuciones paralelas.
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +              <p>La concurrencia y el paralelismo nos brinda bastantes herramientas para que la modelación de dichos procesos se realice de manera más apegada a la realidad, y así mismo, encontrar fo
```suggestion
              <p>La concurrencia y el paralelismo nos brindan bastantes herramientas para que la modelación de dichos procesos se realice de manera más apegada a la realidad y, así mismo, para encontrar formas de que estos procesos sean más eficientes al poder separarlos y distribuirlos en pequeños subprocesos que los conformen y se ejecuten en paralelo, es decir, de una manera ligeramente más natural que una ejecución secuencial.
```
En la última oración se eliminaron las cacofonías causadas por los adverbios terminados en -mente.

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +              <p>La concurrencia y el paralelismo son ampliamente utilizados en distintos enfoques y formas de software, hasta el punto, que constantemente utilizamos programas o escribimos código si
```suggestion
              <p>La concurrencia y el paralelismo son ampliamente utilizados en distintos enfoques y formas de software, al punto en que constantemente utilizamos programas o escribimos código sin saber que muchos de estos procesos están paralelizados para brindar una mejor experiencia al usuario. Algunos ejemplos de la utilización de concurrencia y paralelismo en ciertos softwares y sistemas son:</p>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <p>dentro de un sistema operativo, se pueden ejecutar muchos programas y/o procesos al mismo tiempo compartiendo la misma memoria descomponiendolos en subprocesos asignados a distin
```suggestion
                  <p>Dentro de un sistema operativo se pueden ejecutar muchos programas y/o procesos al mismo tiempo y compartiendo la misma memoria. Esto se logra al descomponerlos en subprocesos asignados a distintos núcleos dentro de un procesador.</p>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <h4>Muchos algoritmos se pueden dividir en partes concurrentes</h4>
Este ítem queda muy cerca de la lista anterior por el tamaño de la imagen. Tratar de darle más espacio o reducir el tamaño del gráfico.

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <p>Los motores que soportan la ejecución de videojuegos deben realizar distintos subprocesos que orquestados correctamente componen la experiencia del jugador , como lo son:</p>
```suggestion
                  <p>Los motores que soportan la ejecución de videojuegos deben realizar distintos subprocesos que, orquestados correctamente, componen la experiencia del jugador, como lo son:</p>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +              <p>otros ejemplos puntuales son:</p>
```suggestion
              <p>Otros ejemplos puntuales son:</p>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <li>Servidores Web</li>
```suggestion
                  <li>Servidores web</li>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <li>Calculo numerico</li>
```suggestion
                  <li>Cálculo numérico</li>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +                  <li>Interaccion por GUI</li>
```suggestion
                  <li>Interacción por GUI</li>
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +            <p>En estos ultimos ejemplos, utilizamos la programación concurrente para :<br />
```suggestion
            <p>En estos últimos ejemplos, la programación concurrente se utiliza para:<br />
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
>                - Los videos juegos o se usará para la recuperación de claves, la interfaz gráfica y el procesamiento de
```suggestion
              - Los videojuegos: para la recuperación de claves, la interfaz gráfica y el procesamiento de
```

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +        </div>
Al parecer, esta segunda etiqueta de cierre sobra.

2022-11-22 04:19 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +            <li>Manuel David Medrano Monroy</li>
Este nombre ya se agrega en otro Pull Request. Podrías considerar eliminarlo para que no quede duplicado cuando se acepten ambos.

2022-11-24 23:14 UTC, ferestrepoca approved these changes

2022-11-24 23:14 UTC, merged