2022-II: Info and group Names added in theorical presentation concurrent programming index.html
ferestrepoca/paradigmas-de-programacion pull request #217
Opened 2022-11-21 17:28 UTC by AlejandroUN

2022-11-22 03:54 UTC, jubustamantem requested changes
Revisar cambios sugeridos y aceptar los que se consideren pertinentes.

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				Interbloqueo por lo general implica varios procesos y puede conducir a la terminación del programa.
```suggestion
				Un interbloqueo, por lo general, implica varios procesos y puede conducir a la terminación del programa. 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				El interbloqueo puede ocurrir cuando los procesos se comunican (por ejemplo, dos procesos intentar
```suggestion
				El interbloqueo puede ocurrir cuando los procesos se comunican (por ejemplo, dos procesos intentan 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				enviarse mensajes entre sí simultáneamente y sincrónicamente) pero es un problema más frecuentemente
```suggestion
				enviarse mensajes entre sí de manera simultánea y sincrónica) pero es un problema más frecuentemente 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				asociado con Administración de recursos. En este contexto son necesarios cuatro condiciones para que
```suggestion
				asociado con administración de recursos. En este contexto son necesarios cuatro condiciones para que 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				  <p>Las técnicas para evitar o recuperarse de un punto muerto se basan en negar al menos una de estas condiciones.
```suggestion
				  <p>Las técnicas para evitar (o recuperarse de) un punto muerto se basan en negar, al menos, una de estas condiciones. 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +					Una de las mejores técnicas (aunque poco prácticas) para evitar interbloqueos es Algoritmo del banquero de Dijkstra.
```suggestion
					Una de las mejores técnicas (aunque poco prácticas) para evitar interbloqueos es el algoritmo del banquero de Dijkstra. 
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +					Dijkstra también planteó lo que se ha convertido en un clásico ejemplo ilustrativo en este campo, el de la Filósofos gastronómicos
```suggestion
					Dijkstra también planteó lo que se ha convertido en un clásico ejemplo ilustrativo en este campo: el de los "filósofos gastronómicos".
```
Aquí se podría poner algún enlace externo, o bien mayor información, para saber a qué ejemplo se está haciendo referencia.

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +				Las técnicas para evitar el problema colocan procesos competitivos en un orden de prioridad tal que cuanto más tiempo espera un proceso, mayor es su se convierte en prioridad. Tratar los procesos
Corregir:
- Poner una coma antes de "cuanto más tiempo".
- La frase "mayor es su se convierte" no se entiende; redactarla conforme a lo que se haya querido expresar.
- Sobra un punto después de "circunstancias".

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +			<p>En general (pero no universalmente) se cree que cuando existe competencia entre procesos de igual estatus en un programa concurrente, se debe hacer algún intento para asegurar que los procesos
Eliminar la redundancia, corregir comas y poner punto después de "incorrecto". Dejo el párrafo corregido aquí para que lo copien y lo peguen; esto porque las sugerencias de github fallan al estar todo contenido en una única línea:

En general, se cree que cuando existe competencia entre procesos de igual estatus en un programa concurrente, se debe hacer algún intento para asegurar que los procesos en cuestión progresen uniformemente; es decir, para asegurar que no haya injusticia manifiesta al momento de satisfacer las necesidades de esos procesos. La equidad en un sistema concurrente se puede considerar tanto a nivel de diseño como de implementación del sistema. Para el diseñador es simplemente una pauta a observar al desarrollar un programa; cualquier descuido de la equidad puede conducir a un aplazamiento indefinido, dejando el programa incorrecto.

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +			<p>Independientemente del entorno en el que se desarrolle un programa concurrente ejecutado, rara vez es aceptable que cualquiera de sus procesos ejecute un bucle en espera de un cambio de estado
Párrafo corregido:

Independientemente del entorno en el que se desarrolle un programa concurrente ejecutado, rara vez es aceptable que cualquiera de sus procesos ejecute un bucle en espera de un cambio de estado del programa. Esto se conoce como "ocupado esperando". Las variables de estado involucradas constituyen un bloqueo de giro. No es en sí mismo un error, pero desperdicia energía del procesador, lo que a su vez puede conducir a la violación de un requisito de desempeño. Idealmente, la ejecución del proceso en cuestión debe suspenderse y continuar sólo cuando se cumple la condición para que progrese.

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
> +			<p>En presencia de no determinismo, fallas en un programa concurrente
```suggestion
			<p>En presencia de no determinismo, las fallas en un programa concurrente
```

2022-11-22 03:54 UTC, jubustamantem commented on progconcurrente/concurrente_teoria/index.html
>              <p><img src="http://ecoosfera.com/wp-content/imagenes/interseccion.gif" alt=""></p>
Eliminar esta imagen, puesto que no carga.

2022-11-22 13:32 UTC, AlejandroUN commented
Chnages done

2022-11-22 13:32 UTC, AlejandroUN commented
Changes done to accept Pull Request

2022-11-24 13:06 UTC, jubustamantem approved these changes
Perfecto. Muchas gracias.

2022-11-24 22:52 UTC, merged