Aporte concurrencia
ferestrepoca/paradigmas-de-programacion pull request #230
Opened 2023-05-25 03:40 UTC by dmojicam

integrantes:
Diego Efrain Mojica Mendez
Juliana Cardozo Pedraza
Juan Sebastian Peñafiel Ojeda
Carlos Andres Rios Rojas
Ejemplo gophers en concurrencia vs paralela, organización del documento, definiciones e información sobre aplicaciones

2023-05-25 23:48 UTC, jdbu2002 approved these changes
Reorganizan la sección de concurrencia haciendola más fácil de leer, y actualizan los assets de imagenes de la sección

2023-05-26 00:07 UTC, ferestrepoca requested changes
Por favor corregir los errores ortográficos para poder hacer el merge.

2023-05-27 20:50 UTC, dmojicam commented
Ya se corrigió la ortografía, ¿Aparece directamente en el pull request o se necesita hacer uno nuevo?

2023-05-27 22:15 UTC, ferestrepoca approved these changes
Así está bien. Gracias.

2023-05-27 22:15 UTC, merged