Programación paralela
ferestrepoca/paradigmas-de-programacion pull request #97
Opened 2018-05-23 17:06 UTC by Yelis3

Juan Pablo Ovalle
José David Nieto
Yeliana Andrea Torres

2018-05-23 18:32 UTC, ferestrepoca requested changes
En este commit se eliminan algunas imágenes de poa/tutoriales/aspectJ/tutorial/images/

Por favor no eliminar nada que no tenga que ver con programación paralela.

2018-05-23 18:35 UTC, ferestrepoca requested changes
Por favor incluir sus nombres en el footer para que quede registro de quienes han contribuido a la página.

2018-05-24 01:12 UTC, dduartec commented
Buenas noches profesor, sin querer le di a "close request", pero no se si los cambios quedaron guardados o no. Somos el grupo de POA.  Perdon por los inconvenientes

2018-05-24 14:17 UTC, ferestrepoca approved these changes

2018-05-24 14:18 UTC, ferestrepoca commented
Falta atender el comentario acerca de no eliminar imágenes de poa/tutoriales/aspectJ/tutorial/images/
Por favor no eliminar nada que no tenga que ver con programación paralela.

2018-05-24 19:13 UTC, merged